---
title: "Mesocosm experiment: Mesocosm data analysis"
author: "Laure Olazcuaga"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: "journal"
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all()

```


# DATASET
## Open dataset
```{r }
#####################
## 1 ## POP SIZE 
#####################
data_size <-  read.csv(file=here::here("data",
                                          "Data_popsize_mesocosm_Asellus2025.csv"))
head(data_size)


# As factor
data_size$Tpop <- as.factor(data_size$Tpop)
data_size$Pop <- as.factor(data_size$Pop)
data_size$Predpop <- as.factor(data_size$Predpop)
data_size$Present_Study <- as.factor(data_size$Present_Study)

data_size$Date <- as.Date(lubridate::dmy(paste0("01-", data_size$Date)))



data_size_here <- data_size[data_size$Present_Study=="yes",]
pd <- position_dodge(0.25) # move them .05 to the left and right




#####################
## 2 ## TEMPERATURE
#####################
final_data_clean_mean_perday <-  read.csv(file=here::here("data",
                                          "Data_temperature_mesocosm_Asellus2025.csv"))


final_data_clean_mean_perday$Day <- as.Date(final_data_clean_mean_perday$Day)

final_data_clean_mean_perday$Tpop <- as.factor(final_data_clean_mean_perday$Tpop)
head(final_data_clean_mean_perday)

#####################
## 3 ##  PHOTO
#####################
photo_img <- png::readPNG(here::here("figures",
                                          "DJI_0412rog.png"))

photo_cropped <- photo_img[1200:4300 , 1000:7100, ]
photo_grob <- grid::rasterGrob(photo_cropped)
photo_plot <- cowplot::ggdraw() + cowplot::draw_grob(photo_grob)
photo_plot

``` 








# FIGURE
## Pop size : Figure All pop
```{r }
 pd = position_dodge(width = 0.1) 

#pd <- position_dodge(width = 3, )

# On crée une variable combinée pour le mapping couleur/fill
data_size$color_group <- interaction(data_size$Predpop, data_size$Tpop)

plot_popsize <- ggplot(data = data_size,
                       aes(x = Date,
                           y = Census,
                           group = interaction(Pop, Present_Study),
                           color = color_group))+
geom_line(aes(linetype = Present_Study),
    position = pd, size = 1, alpha = 0.8) +
geom_point(shape = 21, position = pd, size = 3, alpha = 1, fill= "white", stroke = 1.1) +
geom_point( aes(fill = ifelse(Present_Study == "yes",
                              as.character(color_group), "white") ),
            shape = 21, position = pd, size = 3, alpha = 0.7, stroke = 1.1) +
  scale_color_manual(name = "Evolution history",
    labels = c("Ctrl.Ambiant" = "Ambient x NoPred",
      "Pred.Ambiant" = "Ambient x Pred",
      "Ctrl.Warm"    = "Warm x NoPred",
      "Pred.Warm"    = "Warm x Pred"),
    values = c("Ctrl.Ambiant" = "#92c5de",
      "Pred.Ambiant" = "#0571b0",
      "Ctrl.Warm"    = "#f4a582",
      "Pred.Warm"    = "#ca0020")) +
  scale_fill_manual(name = "Present in study",
    values = c( "Ctrl.Ambiant" = "#92c5de",
      "Pred.Ambiant" = "#0571b0",
      "Ctrl.Warm"    = "#f4a582",
      "Pred.Warm"    = "#ca0020",
      "white" = "white"),
    labels = c("white" = "No", "Ctrl.Ambiant" = "Yes",
               "Pred.Ambiant" = "Yes", "Ctrl.Warm" = "Yes",
               "Pred.Warm" = "Yes") ) +
  scale_linetype_manual( name = "Present in study",
    values = c("no" = "dashed", "yes" = "solid"),
    labels = c("no" = "No", "yes" = "Yes")) +
  #xlab("Year") +
  ylab("Population size") +
    scale_x_date(
    date_labels = "%b %Y",
    breaks = as.Date(c("2019-05-01", "2020-10-01", "2021-05-01"))) +
theme_LO_sobre +
theme(panel.grid.minor = element_blank(),
      panel.grid.major.x = element_blank())
plot_popsize

 
# cowplot::save_plot("Plot_PopSize_PriorExp_SupMat.pdf",
#                    plot_popsize, base_height = 9/cm(1),
#                    base_width = 10/cm(1), dpi = 610)
#  




plot_legend <- ggplot(data = data_size, 
                      aes(x = Date, y = Census, 
                          group = interaction(Pop, Present_Study), 
                          color = color_group)) +
  geom_line(aes(linetype = Present_Study), 
            position = pd, size = 1, alpha = 0.8) +
  geom_point(aes(fill = Present_Study), shape = 21, 
             position = pd, size = 3, alpha = 0.7, stroke = 1.1) +
  scale_color_manual(name = "Evolutionary conditions",
                     labels = c("Ctrl.Ambiant" = "Ambient x Predator-free",
                                "Pred.Ambiant" = "Ambient x Predator",
                                "Ctrl.Warm" = "Warm x Predator-free",
                                "Pred.Warm" = "Warm x Predator"),
                     values = c("Ctrl.Ambiant" = "#92c5de", 
                                "Pred.Ambiant" = "#0571b0",
                                "Ctrl.Warm" = "#f4a582",
                                "Pred.Warm" = "#ca0020")) +
  scale_fill_manual(name = "Present in this study",
                    values = c("no" = "white", "yes" = "black"),
                    labels = c("yes" = "Yes", "no" = "No")) +
  scale_linetype_manual(values = c("no" = "dashed", "yes" = "solid"), guide = "none") +
  scale_x_date(date_labels = "%b %Y", breaks = as.Date(c("2019-05-01", "2020-10-01", "2021-05-01"))) +
  ylab("Population size") +
  theme_LO_sobre +
  theme(panel.grid.minor = element_blank(), panel.grid.major.x = element_blank())

legend <- cowplot::get_legend(plot_legend)
legend_plot <- cowplot::ggdraw(legend)

 
PLOT_PopSoze_legend <- cowplot::ggdraw() + 
  cowplot::draw_plot(plot_popsize +
                       guides(linetype = FALSE, 
                              fill = FALSE, 
                              color = FALSE),
            x = 0, y = 0, width = 0.78, height = 1) + 
  cowplot::draw_plot(legend_plot,
            x = 0.58, y = 0.2, width = 0.6, height = 0.6) 
PLOT_PopSoze_legend


# 
# cowplot::save_plot("Plot_Fig1_PopSize_PriorExp_SupMat_legend.pdf",
#                    PLOT_PopSoze_legend, base_height = 10/cm(1),
#                    base_width = 16/cm(1), dpi = 610)
# 
# #

``` 

## Pop size: pop present here - Fig1A
```{r }

library(dplyr)
data_size$color_group <- interaction(data_size$Predpop, data_size$Tpop)

# Calculer moyenne et IC95% par Date et traitement (color_group)
data_summary <- data_size %>%
  group_by(Date, color_group) %>%
  summarise(mean_census = mean(Census, na.rm = TRUE),
    se = sd(Census, na.rm = TRUE) / sqrt(n()),
    n = n(),
    ci95 = 1.96 * se)

#pd <- position_dodge(width = 3, )

 pd = position_dodge(width = 30) 
Sys.setlocale("LC_TIME", "C")

plot_popsize_mean <- ggplot(data_summary,
                            aes(x = Date, 
                                y = mean_census, 
                                color = color_group)) +
  geom_line(aes(linetype = color_group), 
            size = 0.8, alpha = 0.5,  position =pd) +
  geom_point(aes(shape = color_group), 
            size = 4, position = pd) +
  geom_errorbar(aes(ymin = mean_census - se,
                    ymax = mean_census + se),
                width = 0,             # largeur de la barre horizontale
                size = 0.8,              # épaisseur de la barre
                alpha = 0.8, , position = pd) +
  scale_color_manual(name = "Evolutionary conditions",
                     labels = c("Ctrl.Ambiant" = "Ambient x Predator-free",
                                "Pred.Ambiant" = "Ambient x Predator",
                                "Ctrl.Warm" = "Warm x Predator-free",
                                "Pred.Warm" = "Warm x Predator"),
                     values = c("Ctrl.Ambiant" = "#92c5de", 
                                "Pred.Ambiant" = "#0571b0",
                                "Ctrl.Warm" = "#f4a582",
                                "Pred.Warm" = "#ca0020")) +
  scale_linetype_manual(name = "Evolutionary conditions",
                     labels = c("Ctrl.Ambiant" = "Ambient x Predator-free",
                                "Pred.Ambiant" = "Ambient x Predator",
                                "Ctrl.Warm" = "Warm x Predator-free",
                                "Pred.Warm" = "Warm x Predator"),
                     values = c("Ctrl.Ambiant" = "dashed", 
                                "Pred.Ambiant" = 'dashed',
                                "Ctrl.Warm" = "solid",
                                "Pred.Warm" = "solid")) +
  scale_shape_manual(name = "Evolutionary conditions",
                     labels = c("Ctrl.Ambiant" = "Ambient x Predator-free",
                                "Pred.Ambiant" = "Ambient x Predator",
                                "Ctrl.Warm" = "Warm x Predator-free",
                                "Pred.Warm" = "Warm x Predator"),
                     values = c("Ctrl.Ambiant" = 16, 
                                "Pred.Ambiant" = 17,
                                "Ctrl.Warm" = 16,
                                "Pred.Warm" = 17)) +
  ylab("Population size") +
  scale_x_date(date_labels = "%b %Y",
               breaks = as.Date(c("2019-05-01", "2020-10-01", "2021-05-01"))) +
  theme_LO_sobre +
  theme(panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank())

plot_popsize_mean


# cowplot::save_plot("Plot_Fig1_PopSize_PriorExperiment.pdf",
#                    plot_popsize_mean, base_height = 10/cm(1),
#                    base_width = 16/cm(1), dpi = 610)
# 
# # 

``` 


## Temperature
```{r }


#Plot 
plot_temp <- ggplot(data = final_data_clean_mean_perday[final_data_clean_mean_perday$Day>as.Date("2019-03-01"),]) +
  aes(x = Day , y = Temperature_moy, colour = Tpop, fill = Tpop) +
  geom_point(alpha = 0.1, size = 0.1) +
  geom_smooth(method = "gam", aes(group = Tpop), alpha = 0.5) + 
  labs(x = "Date",
       y = "Temperature",
       colour = "Evolutionary\nconditions",
       fill = "Evolutionary\nconditions") +
  scale_color_manual(values = c("Ambient" ="#0571b0", "Warm" = "#ca0020"),
                     na.translate = FALSE) +
  scale_fill_manual(values = c("Ambient" = "#0571b0", "Warm" = "#ca0020"),
                    na.translate = FALSE) +
  theme_LO_sobre + 
  geom_vline(xintercept = as.Date("2019-07-01"), 
             col = "grey80", linetype ="dashed") + # Pour représenter les sessions de recaptures
  geom_vline(xintercept = as.Date("2022-12-01"), 
             col = "grey80", linetype ="dashed") # Pour représenter les sessions de recaptures
  # theme(text = element_text(size = 16),
  #       legend.title = element_text(size = 14),      # titre légende plus petit
  #       legend.text = element_text(size = 12))       # texte légende plus petit)
plot_temp

# cowplot::save_plot("Temp_mesocosm.pdf",
#                    plot_temp, base_height = 10/cm(1),
#                    base_width = 16/cm(1), dpi = 610)
# 
# # 


``` 



# FIGUREs
## Merge
```{r }




final_plot <- cowplot::ggdraw() +
  cowplot::draw_plot(photo_plot, x = 0.05, y = 0.5, width = 0.38, height = 0.55) +
  cowplot::draw_plot(plot_temp, x = 0, y = 0, width = 0.46, height = 0.6) +
  cowplot::draw_plot(plot_popsize_mean, x = 0.45, y = 0, width = 0.55, height = 0.95) +
  cowplot::draw_plot_label(
    c("A", "B", "C"),
    x = c(0.01, 0.01, 0.45),
    y = c(0.99, 0.61, 0.99),
    hjust = -0.25,
    vjust = 1.5,
    size = 16)
final_plot


# cowplot::save_plot(file=here::here("figures","Plot_Fig1_Mesocosm.pdf"),
#                    final_plot, base_height = 12/cm(1),
#                    base_width = 23/cm(1), dpi = 610)

#

``` 


